dependencies:
- name: template-node-cshell
  version: 0.0.2
  repository: https://artifactory-tools.workshop-ocp46-two-bb0dafd08526894d1a8ae848e8bd8099-0000.us-east.containers.appdomain.cloud/artifactory/generic-local/workshop-team-two

